### ISSUE TITLE
Temporary git with examples?

### ISSUE THREAD

**Issue by zvezdochiot** [mnhrdt/imscript#11]
Maybe a temporary git do with examples? How https://github.com/ImageProcessing-ElectronicPublications/photoquick-examples ?

**Comment by mnhrdt** [comment]
There is the imscript tutorial: http://gabarro.org/ccn/itut/i.html

The images are automatically generated from the code examples, so it is always up to date.

Are there any examples you would find useful to be added to the tutorial?

**Comment by zvezdochiot** [comment]
http://gabarro.org/ccn/itut/i.html
