### ISSUE TITLE
Errorin make file

### ISSUE THREAD

**Issue by pankajsharma47** [mnhrdt/imscript#12]
When i am trying to use make command, it generates error for certain line. What should i do?

src/rpctk.c:79:13: error: array type has incomplete element type ‘struct rpc’
   79 |  struct rpc r[1];
      |             ^
src/rpctk.c: At top level:
src/rpctk.c:95:36: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
   95 | static double rpc_fitL_full(struct rpc *r, double *ijhll, int n)
      |                                    ^~~
src/rpctk.c: In function ‘rpc_fitL_full’:
src/rpctk.c:129:3: error: dereferencing pointer to incomplete type ‘struct rpc’
  129 |  r->scale[0]   = (max_i - min_i) / 2;
      |   ^~
src/rpctk.c: In function ‘main_rpctk_fillL’:
src/rpctk.c:211:13: error: array type has incomplete element type ‘struct rpc’
  211 |  struct rpc r[1];
      |             ^
src/rpctk.c: In function ‘main_rpctk_fitL’:
src/rpctk.c:251:13: error: array type has incomplete element type ‘struct rpc’
  251 |  struct rpc r[1];
      |             ^

**Comment by mnhrdt** [comment]
Can you please provide the complete output of the make command (including stdout and stderr), as well as the details of your system?
