### ISSUE TITLE
Help regarding bin folder generation

### ISSUE THREAD

**Issue by pankajsharma47** [mnhrdt/imscript#13]
Can anyone please upload the bin folder generated after execution of make command. I am getting an error and i am not able to resolve that. 
Thank you.

**Comment by mnhrdt** [comment]
If you show us the error we may be able to help.

The actual contents of the bin folder will depend on your computer architecture and operating system.  For my intel laptop running GNU/linux and compiling without machine-specific optimizations, I got the files attached below
[bin.tar.gz](https://github.com/mnhrdt/imscript/files/6553813/bin.tar.gz)

**Comment by pankajsharma47** [comment]
> If you show us the error we may be able to help.
> 
> The actual contents of the bin folder will depend on your computer architecture and operating system. For my intel laptop running GNU/linux and compiling without machine-specific optimizations, I got the files attached below
> [bin.tar.gz](https://github.com/mnhrdt/imscript/files/6553813/bin.tar.gz)

[bin.zip](https://github.com/mnhrdt/imscript/files/6554659/bin.zip)
This is the output I am getting by using make command. These files are not working and are not generated completely and giving me error as I mentioned in last issue.

**Comment by mnhrdt** [comment]
These files look good to me.  I can run them on a vm without trouble.  How do you know that they are not working?  Can you please post the output of "make test" here?

**Comment by pankajsharma47** [comment]
cc -O3 -march=native   -c -o src/rpctk.o src/rpctk.c
In file included from src/ftr/rpc2.c:11,
                 from src/rpctk.c:21:
src/ftr/xfopen.c:1:1: error: expected identifier or ‘(’ before ‘.’ token
    1 | ../xfopen.c
      | ^
In file included from src/rpctk.c:21:
src/ftr/rpc2.c:37:28: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
   37 | static void nan_rpc(struct rpc *p)
      |                            ^~~
src/ftr/rpc2.c: In function ‘nan_rpc’:
src/ftr/rpc2.c:39:17: error: dereferencing pointer to incomplete type ‘struct rpc’
   39 |  int nd = sizeof*p/sizeof(double);
      |                 ^~
src/ftr/rpc2.c: In function ‘strhas’:
src/ftr/rpc2.c:55:12: warning: implicit declaration of function ‘strstr’ [-Wimplicit-function-declaration]
   55 |  char *r = strstr(haystack, needle);
      |            ^~~~~~
src/ftr/rpc2.c:55:12: warning: incompatible implicit declaration of built-in function ‘strstr’
src/ftr/rpc2.c:12:1: note: include ‘<string.h>’ or provide a declaration of ‘strstr’
   11 | #include "xfopen.c"
  +++ |+#include <string.h>
   12 | 
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:83:35: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
   83 | static void add_tag_to_rpc(struct rpc *p, char *tag, double x)
      |                                   ^~~
src/ftr/rpc2.c: In function ‘add_tag_to_rpc’:
src/ftr/rpc2.c:88:51: error: dereferencing pointer to incomplete type ‘struct rpc’
   88 |  else if (0 == strhas(tag, "SAMP_OFF"))          p->offset [0] = x;
      |                                                   ^~
src/ftr/rpc2.c: In function ‘get_tagged_number’:
src/ftr/rpc2.c:139:2: warning: implicit declaration of function ‘strncpy’ [-Wimplicit-function-declaration]
  139 |  strncpy(tag, buf, 0x100);
      |  ^~~~~~~
src/ftr/rpc2.c:139:2: warning: incompatible implicit declaration of built-in function ‘strncpy’
src/ftr/rpc2.c:139:2: note: include ‘<string.h>’ or provide a declaration of ‘strncpy’
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:182:34: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  182 | void read_rpc_file_ikonos(struct rpc *p, char *filename)
      |                                  ^~~
src/ftr/rpc2.c: In function ‘read_rpc_file_ikonos’:
src/ftr/rpc2.c:184:12: warning: implicit declaration of function ‘xfopen’; did you mean ‘fopen’? [-Wimplicit-function-declaration]
  184 |  FILE *f = xfopen(filename, "r");
      |            ^~~~~~
      |            fopen
src/ftr/rpc2.c:184:12: warning: initialization of ‘FILE *’ {aka ‘struct _IO_FILE *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
src/ftr/rpc2.c:193:19: warning: passing argument 1 of ‘add_tag_to_rpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  193 |    add_tag_to_rpc(p, tag, x);
      |                   ^
      |                   |
      |                   struct rpc *
src/ftr/rpc2.c:83:40: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
   83 | static void add_tag_to_rpc(struct rpc *p, char *tag, double x)
      |                            ~~~~~~~~~~~~^
src/ftr/rpc2.c:196:2: warning: implicit declaration of function ‘xfclose’; did you mean ‘fclose’? [-Wimplicit-function-declaration]
  196 |  xfclose(f);
      |  ^~~~~~~
      |  fclose
src/ftr/rpc2.c:197:3: error: dereferencing pointer to incomplete type ‘struct rpc’
  197 |  p->ioffset[2] = p->offset[2];
      |   ^~
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:201:40: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  201 | void read_rpc_file_xml_pleiades(struct rpc *p, char *filename)
      |                                        ^~~
src/ftr/rpc2.c: In function ‘read_rpc_file_xml_pleiades’:
src/ftr/rpc2.c:203:12: warning: initialization of ‘FILE *’ {aka ‘struct _IO_FILE *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  203 |  FILE *f = xfopen(filename, "r");
      |            ^~~~~~
src/ftr/rpc2.c:213:19: warning: passing argument 1 of ‘add_tag_to_rpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  213 |    add_tag_to_rpc(p, tag+o, x);
      |                   ^
      |                   |
      |                   struct rpc *
src/ftr/rpc2.c:83:40: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
   83 | static void add_tag_to_rpc(struct rpc *p, char *tag, double x)
      |                            ~~~~~~~~~~~~^
src/ftr/rpc2.c:221:3: error: dereferencing pointer to incomplete type ‘struct rpc’
  221 |  p->offset[0] -= 1;
      |   ^~
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:227:41: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  227 | void read_rpc_file_xml_worldview(struct rpc *p, char *filename)
      |                                         ^~~
src/ftr/rpc2.c: In function ‘read_rpc_file_xml_worldview’:
src/ftr/rpc2.c:229:12: warning: initialization of ‘FILE *’ {aka ‘struct _IO_FILE *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  229 |  FILE *f = xfopen(filename, "r");
      |            ^~~~~~
src/ftr/rpc2.c:236:19: warning: passing argument 1 of ‘add_tag_to_rpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  236 |    add_tag_to_rpc(p, tag, x);
      |                   ^
      |                   |
      |                   struct rpc *
src/ftr/rpc2.c:83:40: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
   83 | static void add_tag_to_rpc(struct rpc *p, char *tag, double x)
      |                            ~~~~~~~~~~~~^
src/ftr/rpc2.c:246:21: warning: passing argument 1 of ‘add_tag_to_rpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  246 |      add_tag_to_rpc(p, buf, y[i]);
      |                     ^
      |                     |
      |                     struct rpc *
src/ftr/rpc2.c:83:40: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
   83 | static void add_tag_to_rpc(struct rpc *p, char *tag, double x)
      |                            ~~~~~~~~~~~~^
src/ftr/rpc2.c:251:3: error: dereferencing pointer to incomplete type ‘struct rpc’
  251 |  p->ioffset[2] = p->offset[2];
      |   ^~
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:257:31: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  257 | void read_rpc_file_xml(struct rpc *p, char *filename)
      |                               ^~~
src/ftr/rpc2.c: In function ‘read_rpc_file_xml’:
src/ftr/rpc2.c:259:10: warning: passing argument 1 of ‘nan_rpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  259 |  nan_rpc(p);
      |          ^
      |          |
      |          struct rpc *
src/ftr/rpc2.c:37:33: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
   37 | static void nan_rpc(struct rpc *p)
      |                     ~~~~~~~~~~~~^
src/ftr/rpc2.c:260:12: warning: initialization of ‘FILE *’ {aka ‘struct _IO_FILE *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  260 |  FILE *f = xfopen(filename, "r");
      |            ^~~~~~
src/ftr/rpc2.c:268:36: warning: passing argument 1 of ‘add_tag_to_rpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  268 |    if (isfinite(x)) add_tag_to_rpc(p, tag, x);
      |                                    ^
      |                                    |
      |                                    struct rpc *
src/ftr/rpc2.c:83:40: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
   83 | static void add_tag_to_rpc(struct rpc *p, char *tag, double x)
      |                            ~~~~~~~~~~~~^
src/ftr/rpc2.c:269:25: warning: passing argument 1 of ‘read_rpc_file_ikonos’ from incompatible pointer type [-Wincompatible-pointer-types]
  269 |    read_rpc_file_ikonos(p, filename);
      |                         ^
      |                         |
      |                         struct rpc *
src/ftr/rpc2.c:182:39: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  182 | void read_rpc_file_ikonos(struct rpc *p, char *filename)
      |                           ~~~~~~~~~~~~^
src/ftr/rpc2.c:274:32: warning: passing argument 1 of ‘read_rpc_file_xml_worldview’ from incompatible pointer type [-Wincompatible-pointer-types]
  274 |    read_rpc_file_xml_worldview(p, filename);
      |                                ^
      |                                |
      |                                struct rpc *
src/ftr/rpc2.c:227:46: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  227 | void read_rpc_file_xml_worldview(struct rpc *p, char *filename)
      |                                  ~~~~~~~~~~~~^
src/ftr/rpc2.c:279:31: warning: passing argument 1 of ‘read_rpc_file_xml_pleiades’ from incompatible pointer type [-Wincompatible-pointer-types]
  279 |    read_rpc_file_xml_pleiades(p, filename);
      |                               ^
      |                               |
      |                               struct rpc *
src/ftr/rpc2.c:201:45: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  201 | void read_rpc_file_xml_pleiades(struct rpc *p, char *filename)
      |                                 ~~~~~~~~~~~~^
src/ftr/rpc2.c:284:31: warning: passing argument 1 of ‘read_rpc_file_xml_pleiades’ from incompatible pointer type [-Wincompatible-pointer-types]
  284 |    read_rpc_file_xml_pleiades(p, filename);
      |                               ^
      |                               |
      |                               struct rpc *
src/ftr/rpc2.c:201:45: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  201 | void read_rpc_file_xml_pleiades(struct rpc *p, char *filename)
      |                                 ~~~~~~~~~~~~^
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:292:32: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  292 | void print_rpc(FILE *f, struct rpc *p, char *n)
      |                                ^~~
src/ftr/rpc2.c: In function ‘print_rpc’:
src/ftr/rpc2.c:294:57: error: dereferencing pointer to incomplete type ‘struct rpc’
  294 |  FORI(20) fprintf(f, "rpc(%s) numx[%d] = %.18lf\n",n,i,p->numx[i]);
      |                                                         ^~
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:392:40: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  392 | static void eval_nrpc(double *, struct rpc *, double, double, double);
      |                                        ^~~
src/ftr/rpc2.c:393:41: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  393 | static void eval_nrpci(double *, struct rpc *, double, double, double);
      |                                         ^~~
src/ftr/rpc2.c:398:10: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  398 |   struct rpc *p, double x, double y, double z)
      |          ^~~
src/ftr/rpc2.c: In function ‘eval_nrpc_iterative’:
src/ftr/rpc2.c:406:17: warning: passing argument 2 of ‘eval_nrpci’ from incompatible pointer type [-Wincompatible-pointer-types]
  406 |  eval_nrpci(x0, p, lon, lat, z);
      |                 ^
      |                 |
      |                 struct rpc *
src/ftr/rpc2.c:393:34: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  393 | static void eval_nrpci(double *, struct rpc *, double, double, double);
      |                                  ^~~~~~~~~~~~
src/ftr/rpc2.c:407:17: warning: passing argument 2 of ‘eval_nrpci’ from incompatible pointer type [-Wincompatible-pointer-types]
  407 |  eval_nrpci(x1, p, lon + eps, lat, z);
      |                 ^
      |                 |
      |                 struct rpc *
src/ftr/rpc2.c:393:34: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  393 | static void eval_nrpci(double *, struct rpc *, double, double, double);
      |                                  ^~~~~~~~~~~~
src/ftr/rpc2.c:408:17: warning: passing argument 2 of ‘eval_nrpci’ from incompatible pointer type [-Wincompatible-pointer-types]
  408 |  eval_nrpci(x2, p, lon, lat + eps, z);
      |                 ^
      |                 |
      |                 struct rpc *
src/ftr/rpc2.c:393:34: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  393 | static void eval_nrpci(double *, struct rpc *, double, double, double);
      |                                  ^~~~~~~~~~~~
src/ftr/rpc2.c:419:18: warning: passing argument 2 of ‘eval_nrpci’ from incompatible pointer type [-Wincompatible-pointer-types]
  419 |   eval_nrpci(x0, p, lon, lat, z);
      |                  ^
      |                  |
      |                  struct rpc *
src/ftr/rpc2.c:393:34: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  393 | static void eval_nrpci(double *, struct rpc *, double, double, double);
      |                                  ^~~~~~~~~~~~
src/ftr/rpc2.c:420:18: warning: passing argument 2 of ‘eval_nrpci’ from incompatible pointer type [-Wincompatible-pointer-types]
  420 |   eval_nrpci(x1, p, lon + eps, lat, z);
      |                  ^
      |                  |
      |                  struct rpc *
src/ftr/rpc2.c:393:34: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  393 | static void eval_nrpci(double *, struct rpc *, double, double, double);
      |                                  ^~~~~~~~~~~~
src/ftr/rpc2.c:421:18: warning: passing argument 2 of ‘eval_nrpci’ from incompatible pointer type [-Wincompatible-pointer-types]
  421 |   eval_nrpci(x2, p, lon, lat + eps, z);
      |                  ^
      |                  |
      |                  struct rpc *
src/ftr/rpc2.c:393:34: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  393 | static void eval_nrpci(double *, struct rpc *, double, double, double);
      |                                  ^~~~~~~~~~~~
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:428:10: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  428 |   struct rpc *p, double x, double y, double z)
      |          ^~~
In file included from src/ftr/rpc2.c:3,
                 from src/rpctk.c:21:
src/ftr/rpc2.c: In function ‘eval_nrpci_iterative’:
src/ftr/rpc2.c:430:19: error: dereferencing pointer to incomplete type ‘struct rpc’
  430 |  assert(isfinite(p->numx[0]));
      |                   ^~
In file included from src/rpctk.c:21:
src/ftr/rpc2.c:437:16: warning: passing argument 2 of ‘eval_nrpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  437 |  eval_nrpc(x0, p, lon, lat, z);
      |                ^
      |                |
      |                struct rpc *
src/ftr/rpc2.c:392:33: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  392 | static void eval_nrpc(double *, struct rpc *, double, double, double);
      |                                 ^~~~~~~~~~~~
src/ftr/rpc2.c:438:16: warning: passing argument 2 of ‘eval_nrpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  438 |  eval_nrpc(x1, p, lon + eps, lat, z);
      |                ^
      |                |
      |                struct rpc *
src/ftr/rpc2.c:392:33: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  392 | static void eval_nrpc(double *, struct rpc *, double, double, double);
      |                                 ^~~~~~~~~~~~
src/ftr/rpc2.c:439:16: warning: passing argument 2 of ‘eval_nrpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  439 |  eval_nrpc(x2, p, lon, lat + eps, z);
      |                ^
      |                |
      |                struct rpc *
src/ftr/rpc2.c:392:33: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  392 | static void eval_nrpc(double *, struct rpc *, double, double, double);
      |                                 ^~~~~~~~~~~~
src/ftr/rpc2.c:450:17: warning: passing argument 2 of ‘eval_nrpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  450 |   eval_nrpc(x0, p, lon, lat, z);
      |                 ^
      |                 |
      |                 struct rpc *
src/ftr/rpc2.c:392:33: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  392 | static void eval_nrpc(double *, struct rpc *, double, double, double);
      |                                 ^~~~~~~~~~~~
src/ftr/rpc2.c:451:17: warning: passing argument 2 of ‘eval_nrpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  451 |   eval_nrpc(x1, p, lon + eps, lat, z);
      |                 ^
      |                 |
      |                 struct rpc *
src/ftr/rpc2.c:392:33: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  392 | static void eval_nrpc(double *, struct rpc *, double, double, double);
      |                                 ^~~~~~~~~~~~
src/ftr/rpc2.c:452:17: warning: passing argument 2 of ‘eval_nrpc’ from incompatible pointer type [-Wincompatible-pointer-types]
  452 |   eval_nrpc(x2, p, lon, lat + eps, z);
      |                 ^
      |                 |
      |                 struct rpc *
src/ftr/rpc2.c:392:33: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  392 | static void eval_nrpc(double *, struct rpc *, double, double, double);
      |                                 ^~~~~~~~~~~~
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:460:10: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  460 |   struct rpc *p, double x, double y, double z)
      |          ^~~
src/ftr/rpc2.c:459:13: error: conflicting types for ‘eval_nrpc’
  459 | static void eval_nrpc(double *result,
      |             ^~~~~~~~~
src/ftr/rpc2.c:392:13: note: previous declaration of ‘eval_nrpc’ was here
  392 | static void eval_nrpc(double *, struct rpc *, double, double, double);
      |             ^~~~~~~~~
In file included from src/rpcfit33.c:2,
                 from src/rpctk.c:17:
src/ftr/rpc2.c: In function ‘eval_nrpc’:
src/ftr/rpc2.c:462:16: error: dereferencing pointer to incomplete type ‘struct rpc’
  462 |  if (isfinite(p->numx[0])) {
      |                ^~
In file included from src/rpctk.c:21:
src/ftr/rpc2.c:470:37: warning: passing argument 2 of ‘eval_nrpc_iterative’ from incompatible pointer type [-Wincompatible-pointer-types]
  470 |  } else eval_nrpc_iterative(result, p, x, y, z);
      |                                     ^
      |                                     |
      |                                     struct rpc *
src/ftr/rpc2.c:398:15: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  398 |   struct rpc *p, double x, double y, double z)
      |   ~~~~~~~~~~~~^
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:475:10: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  475 |   struct rpc *p, double x, double y, double z)
      |          ^~~
src/ftr/rpc2.c:474:13: error: conflicting types for ‘eval_nrpci’
  474 | static void eval_nrpci(double *result,
      |             ^~~~~~~~~~
src/ftr/rpc2.c:393:13: note: previous declaration of ‘eval_nrpci’ was here
  393 | static void eval_nrpci(double *, struct rpc *, double, double, double);
      |             ^~~~~~~~~~
In file included from src/rpcfit33.c:2,
                 from src/rpctk.c:17:
src/ftr/rpc2.c: In function ‘eval_nrpci’:
src/ftr/rpc2.c:477:16: error: dereferencing pointer to incomplete type ‘struct rpc’
  477 |  if (isfinite(p->inumx[0])) {
      |                ^~
In file included from src/rpctk.c:21:
src/ftr/rpc2.c:486:38: warning: passing argument 2 of ‘eval_nrpci_iterative’ from incompatible pointer type [-Wincompatible-pointer-types]
  486 |  } else eval_nrpci_iterative(result, p, x, y, z);
      |                                      ^
      |                                      |
      |                                      struct rpc *
src/ftr/rpc2.c:428:15: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  428 |   struct rpc *p, double x, double y, double z)
      |   ~~~~~~~~~~~~^
In file included from src/ftr/rpc2.c:489,
                 from src/rpctk.c:21:
src/ftr/smapa.h: At top level:
src/ftr/smapa.h:1:1: error: expected identifier or ‘(’ before ‘.’ token
    1 | ../smapa.h
      | ^
In file included from src/rpctk.c:21:
src/ftr/rpc2.c:511:10: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  511 |   struct rpc *p, double x, double y, double z)
      |          ^~~
src/ftr/rpc2.c: In function ‘eval_rpci’:
src/ftr/rpc2.c:513:20: error: dereferencing pointer to incomplete type ‘struct rpc’
  513 |  double nx = (x - p->ioffset[0])/p->iscale[0];
      |                    ^~
src/ftr/rpc2.c:517:18: warning: passing argument 2 of ‘eval_nrpci’ from incompatible pointer type [-Wincompatible-pointer-types]
  517 |  eval_nrpci(tmp, p, nx, ny, nz);
      |                  ^
      |                  |
      |                  struct rpc *
In file included from src/rpctk.c:21:
src/ftr/rpc2.c:475:15: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  475 |   struct rpc *p, double x, double y, double z)
      |   ~~~~~~~~~~~~^
In file included from src/rpctk.c:21:
src/ftr/rpc2.c:520:6: warning: implicit declaration of function ‘EVAL_RPC_DEBUG’ [-Wimplicit-function-declaration]
  520 |  if (EVAL_RPC_DEBUG() > 0)
      |      ^~~~~~~~~~~~~~
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:527:10: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  527 |   struct rpc *pa, struct rpc *pb,
      |          ^~~
src/ftr/rpc2.c: In function ‘eval_rpc_pair’:
src/ftr/rpc2.c:531:2: warning: implicit declaration of function ‘eval_rpc’; did you mean ‘eval_rpci’? [-Wimplicit-function-declaration]
  531 |  eval_rpc(tmp, pa, x, y, z);
      |  ^~~~~~~~
      |  eval_rpci
src/ftr/rpc2.c:532:20: warning: passing argument 2 of ‘eval_rpci’ from incompatible pointer type [-Wincompatible-pointer-types]
  532 |  eval_rpci(xprime, pb, tmp[0], tmp[1], z);
      |                    ^~
      |                    |
      |                    struct rpc *
src/ftr/rpc2.c:511:15: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  511 |   struct rpc *p, double x, double y, double z)
      |   ~~~~~~~~~~~~^
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:535:42: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  535 | void rpc_projection(double ij[2], struct rpc *r, double lonlatheight[3])
      |                                          ^~~
src/ftr/rpc2.c: In function ‘rpc_projection’:
src/ftr/rpc2.c:537:16: warning: passing argument 2 of ‘eval_rpci’ from incompatible pointer type [-Wincompatible-pointer-types]
  537 |  eval_rpci(ij, r, lonlatheight[0], lonlatheight[1], lonlatheight[2]);
      |                ^
      |                |
      |                struct rpc *
src/ftr/rpc2.c:511:15: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  511 |   struct rpc *p, double x, double y, double z)
      |   ~~~~~~~~~~~~^
src/ftr/rpc2.c: At top level:
src/ftr/rpc2.c:540:48: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  540 | void rpc_localization(double lonlat[2], struct rpc *r, double ijh[3])
      |                                                ^~~
src/ftr/rpc2.c:551:26: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  551 | double rpc_height(struct rpc *rpca, struct rpc *rpcb,
      |                          ^~~
src/ftr/rpc2.c: In function ‘rpc_height’:
src/ftr/rpc2.c:561:20: warning: passing argument 2 of ‘eval_rpc_pair’ from incompatible pointer type [-Wincompatible-pointer-types]
  561 |   eval_rpc_pair(p, rpca, rpcb, x[0], x[1], h);
      |                    ^~~~
      |                    |
      |                    struct rpc *
src/ftr/rpc2.c:527:15: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  527 |   struct rpc *pa, struct rpc *pb,
      |   ~~~~~~~~~~~~^~
src/ftr/rpc2.c:561:26: warning: passing argument 3 of ‘eval_rpc_pair’ from incompatible pointer type [-Wincompatible-pointer-types]
  561 |   eval_rpc_pair(p, rpca, rpcb, x[0], x[1], h);
      |                          ^~~~
      |                          |
      |                          struct rpc *
src/ftr/rpc2.c:527:31: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  527 |   struct rpc *pa, struct rpc *pb,
      |                   ~~~~~~~~~~~~^~
src/ftr/rpc2.c:562:20: warning: passing argument 2 of ‘eval_rpc_pair’ from incompatible pointer type [-Wincompatible-pointer-types]
  562 |   eval_rpc_pair(q, rpca, rpcb, x[0], x[1], h + hstep);
      |                    ^~~~
      |                    |
      |                    struct rpc *
src/ftr/rpc2.c:527:15: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  527 |   struct rpc *pa, struct rpc *pb,
      |   ~~~~~~~~~~~~^~
src/ftr/rpc2.c:562:26: warning: passing argument 3 of ‘eval_rpc_pair’ from incompatible pointer type [-Wincompatible-pointer-types]
  562 |   eval_rpc_pair(q, rpca, rpcb, x[0], x[1], h + hstep);
      |                          ^~~~
      |                          |
      |                          struct rpc *
src/ftr/rpc2.c:527:31: note: expected ‘struct rpc *’ but argument is of type ‘struct rpc *’
  527 |   struct rpc *pa, struct rpc *pb,
      |                   ~~~~~~~~~~~~^~
src/ftr/rpc2.c: In function ‘main_trial2’:
src/ftr/rpc2.c:595:13: error: array type has incomplete element type ‘struct rpc’
  595 |  struct rpc p[1];
      |             ^
src/ftr/rpc2.c: In function ‘main_trial’:
src/ftr/rpc2.c:621:13: error: array type has incomplete element type ‘struct rpc’
  621 |  struct rpc p[1];
      |             ^
src/ftr/rpc2.c: In function ‘main_rpcline’:
src/ftr/rpc2.c:666:13: error: array type has incomplete element type ‘struct rpc’
  666 |  struct rpc rpca[1]; read_rpc_file_xml(rpca, filename_rpca);
      |             ^~~~
src/ftr/rpc2.c:667:13: error: array type has incomplete element type ‘struct rpc’
  667 |  struct rpc rpcb[1]; read_rpc_file_xml(rpcb, filename_rpcb);
      |             ^~~~
src/ftr/rpc2.c: In function ‘main_rpcpair’:
src/ftr/rpc2.c:709:13: error: array type has incomplete element type ‘struct rpc’
  709 |  struct rpc a[1]; read_rpc_file_xml(a, filename_rpca);
      |             ^
src/ftr/rpc2.c:710:13: error: array type has incomplete element type ‘struct rpc’
  710 |  struct rpc b[1]; read_rpc_file_xml(b, filename_rpcb);
      |             ^
src/rpctk.c: In function ‘main_rpctk_info’:
src/rpctk.c:28:13: error: array type has incomplete element type ‘struct rpc’
   28 |  struct rpc a[1];
      |             ^
src/rpctk.c: In function ‘main_rpctk_localize’:
src/rpctk.c:58:13: error: array type has incomplete element type ‘struct rpc’
   58 |  struct rpc r[1];
      |             ^
src/rpctk.c: In function ‘main_rpctk_project’:
src/rpctk.c:79:13: error: array type has incomplete element type ‘struct rpc’
   79 |  struct rpc r[1];
      |             ^
src/rpctk.c: At top level:
src/rpctk.c:95:36: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
   95 | static double rpc_fitL_full(struct rpc *r, double *ijhll, int n)
      |                                    ^~~
src/rpctk.c: In function ‘rpc_fitL_full’:
src/rpctk.c:129:3: error: dereferencing pointer to incomplete type ‘struct rpc’
  129 |  r->scale[0]   = (max_i - min_i) / 2;
      |   ^~
src/rpctk.c: In function ‘main_rpctk_fillL’:
src/rpctk.c:211:13: error: array type has incomplete element type ‘struct rpc’
  211 |  struct rpc r[1];
      |             ^
src/rpctk.c: In function ‘main_rpctk_fitL’:
src/rpctk.c:251:13: error: array type has incomplete element type ‘struct rpc’
  251 |  struct rpc r[1];
      |             ^
src/rpctk.c: At top level:
src/rpctk.c:262:41: warning: ‘struct rpc’ declared inside parameter list will not be visible outside of this definition or declaration
  262 | static void rescale_rpc_in_place(struct rpc *r, float z)
      |                                         ^~~
src/rpctk.c: In function ‘main_rpctk_zoom’:
src/rpctk.c:275:13: error: array type has incomplete element type ‘struct rpc’
  275 |  struct rpc r[1];
      |             ^
In file included from src/rpctk.c:21:
src/rpctk.c: At top level:
src/ftr/rpc2.c:392:13: warning: ‘eval_nrpc’ used but never defined
  392 | static void eval_nrpc(double *, struct rpc *, double, double, double);
      |             ^~~~~~~~~
src/ftr/rpc2.c:393:13: warning: ‘eval_nrpci’ used but never defined
  393 | static void eval_nrpci(double *, struct rpc *, double, double, double);
      |             ^~~~~~~~~~
make: *** [<builtin>: src/rpctk.o] Error 1

**Comment by mnhrdt** [comment]
This is a very strange problem, as if symbolic links did not work correctly in your filesystem.  Are you compiling over a networked filesystem?  That may cause this sort of problems.  Otherwise I'm at a loss.

I have pushed a modification that may fix this problem in the short term, but other similar problems will probably remain.  Can you check if it works?

**Comment by pankajsharma47** [comment]
Sure, I will give it a try. I am actually using ubantu on oracle virtaul machine.

**Comment by pankajsharma47** [comment]
Have you tried generating bin folder for google colab?

**Comment by mnhrdt** [comment]
No, never used that.  We can add it to CI if possible and desirable.

**Comment by pankajsharma47** [comment]
> No, never used that. We can add it to CI if possible and desirable.

Can you please give it a try. As colab uses ubantu 18.04, it is possible to use it there I guess.

**Comment by mnhrdt** [comment]
I don't see how to use it without a google account, sorry.
