### ISSUE TITLE
macOS build error

### ISSUE THREAD

**Issue by grylem** [mnhrdt/imscript#14]
Hi
macOS Apple M1
make  -j
src/iio.c:569:8: error: duplicate case value '8'
                case sizeof(long double): return IIO_TYPE_LONGDOUBLE;
                     ^
src/iio.c:568:8: note: previous case defined here
                case sizeof(double):      return IIO_TYPE_DOUBLE;
                     ^
1 error generated.

Regards.

**Comment by mnhrdt** [comment]
thanks for notifying this issue!
the last update should solve this problem

**Comment by grylem** [comment]
thanks.
You can also delete a string '-march=native' in makefile then macOS is used.  The latest versions of apple clang do not support it.
