### ISSUE TITLE
lrcar, tbcat output

### ISSUE THREAD

**Issue by grylem** [mnhrdt/imscript#15]
Hi.
imscript compiled with jpeg, webp, png, tiff support, but outputs only for ppm, png, tiff.
lrcat file1.ppm file2.ppm -o combo.webp
lrcat file1.ppm file2.ppm -o combo.jpg(jpeg)

file combo.webp
combo.webp: NumPy data file, version 1.0 ...

Also: how to make output to stdout?

Thanks.

**Comment by mnhrdt** [comment]
> imscript compiled with jpeg, webp, png, tiff support, but outputs only for ppm, png, tiff.

Yes.  Writing lossy formats is not supported.  I could not figure a way to specify the quality of the output file without spoiling the clean api.  See iio's documentation https://github.com/mnhrdt/iio/blob/63699983282e07c01d0bca868f6b0232d954dacd/README#L310 for a list of supported output file formats.

> how to make output to stdout?

Use "-" as a filename to write to stdout (or read for stdin).  For example:

    lrcat a.png b.png -o - | cpu

Notice that sometimes the output file can be omitted (when it is not ambiguous to do so) and then it is stdout by default.  Thus this is equivalent to the previous line:

    lrcat a.pnb b.png | cpu

**Comment by grylem** [comment]
Thanks.
