### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [mnhrdt/imscript#16]
Would you like to add more error handling for return values from functions like the following?
* [calloc](https://pubs.opengroup.org/onlinepubs/9699919799/functions/calloc.html "Memory allocation") ⇒ [svduv](https://github.com/mnhrdt/imscript/blob/41e31fd2ce0592be3ea0328ffb8aed32de99c838/src/misc/svd.c#L128)
* [printf](https://pubs.opengroup.org/onlinepubs/9699919799/functions/printf.html "Print formatted output") ⇒ [dump_histogram](https://github.com/mnhrdt/imscript/blob/b6435e653ae0208f6752e304fa2d1face261fdc2/src/ghisto.c#L66)

**Comment by mnhrdt** [comment]
Is this a bot?  This user posts the same "issues" across many unrelated repos.

**Comment by elfring** [comment]
>Is this a bot?

No.


>This user posts the same "issues" across many unrelated repos.

I dared to point recurring programming mistakes out at various places.

:thought_balloon: I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?
